name: Model Results

on:
  # schedule:
    # - cron: '0 02 * * 6' # e.g. --> cron: '0 20 * * *' (means runs at 4am daily at GMT+08, Singapore time)
  workflow_dispatch: # Create a button to trigger the workflow manually

jobs:
  build:
    runs-on: ubuntu-latest # ubuntu-latest # windows-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Set up credentials
      #   env:
      #     GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLEAPI }}
      #   run: |
      #     echo "$GOOGLE_APPLICATION_CREDENTIALS" > "$HOME"/gcp_key.json
      #     gcloud auth activate-service-account --key-file="$HOME"/gcp_key.json
          
      - name: execute py script
        # env:
        #   GOOGLEAPI: ${{secrets.GOOGLEAPI}}
        run: python main.py result
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
